### ISSUE TITLE
Co-existence with CSS/SASS/LESS files

### ISSUE THREAD

**Issue by sglanzer** [endash/ember-cli-gridstylesheets#2] opened 2015-02-24 20:59 UTC
CSS files appear to be ignored in any projects with this addon.  I'd like the ability to combine CSS and GSS (texture and structure).  Ideally, I'd like the CSS to use a SASS or LESS pre-processor so that I can use import statements and nest the texture CSS files in pod directories.

**Comment by endash** [comment] 2015-02-24 21:22
OK that's a major problem and at first blush I'm not sure why that would be. The preprocessor returns a merged tree (the tree it was passed, and the result of picking the gss files and zipping them up), so it should be transparent to any other addons.

**Comment by sglanzer** [comment] 2015-02-24 21:30
It's possible that it's due to the pre-processor registration.  I'm not sure if it's an array, it may just overwrite any other entries for CSS processing.  I've been poking at the broccoli structure as well, but as you noted in the other issue it's a bit magical in ember-cli.

Awesome project by the way, I had no idea gss even existed prior to this.  How in the world aren't more people using it?

**Comment by endash** [comment] 2015-02-24 21:31
Looking at the ember-cli source I think adding *any* CSS type plugin disables the default CSS behaviour. That makes some sort of sense.

Ultimately the problem is we're tacking onto the CSS plugin type when we don't care about CSS files at all. However not only are the other types even less relevant, but the trees they get handed are generated differently. Ideally there'd be a generic hook that just gave us the project and addons tree straight.

**Comment by endash** [comment] 2015-02-24 21:34
GSS I think suffers from two main marketing problems: (1) It seems at first blush to replace an efficient, native implementation (CSS) with a javascript (GSS), which while strictly true is an overblown complaint since the functionality is so different (2) Apple UI AutoLayout SUCKED for a long time. I only really started grokking it when working on a new app in Swift and I forced myself to use it.

**Comment by sglanzer** [comment] 2015-02-24 21:39
I used this code recently to get SASS compilation working in an addon project - it's possible it could be rejigged to work for gss, since it doesn't hook into any registration methods it might leave it clean.

````
var broccoli_sass = require('broccoli-sass');

function getAddon (addons, name) {
    addons = addons.filter(function(addon) {
        return addon.name === name;
    });
    return addons.length === 1 ? addons[0] : null;
}

module.exports = {
    name: 'my-addon',

    included: function(app) {
        this._super.included(app);

        var addon = getAddon(app.project.addons, 'my-addon');
        if (!addon) { return; }

        addon.treePaths.styles = 'addon/styles';
        addon.treeForStyles = function(tree) {
            tree = broccoli_sass([tree], 'addon.scss', 'vendor/my-addon-texture.css');
            app.vendorStaticStyles.push('vendor/my-addon-texture.css');
            return tree;
        };
    }
};
````

**Comment by endash** [comment] 2015-02-24 21:44
Can you clarify for me what addons you had installed when you encountered this? My working theory gets blown out of the water if there's another CSS preprocessor added to the app registry by an addon. Currently my theory is that if we're the only addon adding a preprocessor, we're causing this code to be skipped:

https://github.com/ember-cli/ember-cli/blob/master/lib/preprocessors.js#L119

If that code would have been skipped *anyway* then there's something else going on.

**Comment by sglanzer** [comment] 2015-02-25 02:19
None that act as css pre-processors in that case - fresh project just experimenting with the addon.  I had a few broccoli packages installed (concat, funnel, merge-trees, stew), but nothing else.

I'll create a new project and try this out again from scratch with progressive additions to make sure there isn't anything additional impacting the results.

**Comment by endash** [comment] 2015-02-25 03:33
In the mean time I'll put together a default-css addon that can be included with this addon in the absence of a real css pre processor addon. Not ideal but better than nothing for now.

**Comment by endash** [comment] 2015-02-25 03:33
In the mean time I'll put together a default-css addon that can be included with this addon in the absence of a real css pre processor addon. Not ideal but better than nothing for now.

**Comment by sglanzer** [comment] 2015-02-25 05:15
Ok, I just threw together a simple project to test this:

1. ember new gss-testbed
2. cd into gss-testbed, ember install:addon ember-cli-gridstylesheets
3. ember generate component gss-box
4. modify the gss-box component to include classNames: ['gss-box', 'gss-box--red']
5. modify styles/app.css to include
````
.gss-box {
  display: inline-block;
  width: 100px;
  height: 100px;
}

.gss-box--red {
  background-color: red;
}
````
6. modify application.hbs to include {{gss-box}}
7. ember server - no red box appears
8. npm uninstall --save-dev ember-cli-gridstylesheets
9. ember server - red box appears

**Comment by sglanzer** [comment] 2015-02-25 05:17
I'll raise an issue against ember-cli tomorrow asking for the appropriate hook to use for non-css pre-processors like this.  The guys on the project have been quite responsive, so hopefully they can give us some direction on how to fix this.

**Comment by endash** [comment] 2015-02-25 07:03
I've gone over ember-app several times now and I'm pretty sure I'm not missing any clear cut solution. The CSS hook seemed the least bad option, since they are still stylesheets after all, although obviously not ideal. Will probably have to abandon the preprocessing avenue entirely, but ember-app pretty aggressively picks out only the files it wants and discards the rest. A last ditch hook to get at the unfiltered app tree and return a tree guaranteed to make it through to dist would be the simplest change to ember-cli but I imagine that would have come up before and thus has been rejected as an option.

Having a second addon to restore default CSS tree behaviour would also only fix the broken css problem. Getting at GSS files from addons would still be an issue.

What I'd like to see is a promotion of js/template/css processing to a set of classes that could be extended horizontally (new types) as well as vertically (hooks for tying into default type behaviour).

**Comment by endash** [comment] 2015-02-25 07:05
One last ditch option if all else fails is to monkey patch the ember-app instance. It goes without saying that would be a horrible outcome.

**Comment by endash** [comment] 2015-02-25 08:27
I've opened up a ticket on ember-cli: https://github.com/ember-cli/ember-cli/issues/3362

**Comment by endash** [comment] 2015-03-07 19:27
Absent a more comprehensive solution from ember-cli I'm contemplating monkey-patching EmberApp#toArray to inject our requisite tree and remove the preprocessor bit entirely.

**Comment by endash** [comment] 2015-03-27 22:48
I finally got around to scrubbing the attempt at using preprocessors and instead I've patched into EmberArray#toArray to add our tree to the regular trees that get created. Not ideal, by a longshot, but now CSS+GSS coexist.

**Closed** 2015-03-27 23:40 UTC
